### ISSUE TITLE
Utilize add_subparsers to unify CLI

### ISSUE THREAD

**Issue by ibnesayeed** [oduwsdl/hypercane#7]
It looks like `argparse` is being used in individual actions which is then called from `bin/hc` where a top-level command (i.e., `hc`) implements arg parsing manually. We could perhaps use `add_subparsers` in the entrypoint script to leverage built-in capabilities on the standard argument parser package. We have used this technique in some of the other WSDL projects.

**Comment by shawnmjones** [comment]
I've experimented with this successfully. What other WSDL projects have used it successfully?

**Comment by ibnesayeed** [comment]
> What other WSDL projects have used it successfully?

* [MementoMap](https://github.com/oduwsdl/MementoMap/blob/master/main.py)
* [IPWB](https://github.com/oduwsdl/ipwb/blob/master/ipwb/__main__.py)

**Comment by shawnmjones** [comment]
Thanks! I'll review that code and see what I can adapt.

**Comment by shawnmjones** [comment]
This was completed by aa8bdaa191147bf817f31d87a4f1a17eb54ec82a as part of the IIPC 2021 DSA Grant.
